### ISSUE TITLE
win-tls thows TLS1.3 error for Windows Server 2019

### ISSUE THREAD

**Issue by automate-this** [Constey/checkmk#1]
Hi.

I just deployed your extension and all my Windows Server 2019 thow a warning because your plugin thinks that TLS 1.3 is enabled?
I double checked the registry and there isn't even an entry
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3

![image](https://github.com/Constey/checkmk/assets/81413189/6adbe111-f774-4bbb-a29a-25af10ae3f9e)

**Comment by automate-this** [comment]
Update:
It seems that the "default warning levels" are not really default.
I had to create the service monitoring rule and enable the default values. now it works.

**Comment by automate-this** [comment]
FYI: I guess you should update the Text in the GUI too. Seems there are some things left from the mkp you copied. :)

![image](https://github.com/Constey/checkmk/assets/81413189/3dfb6989-7cb8-4a05-bb98-1e62542b4860)

**Comment by Constey** [comment]
Thanks for the hints, im checking this :-) Am 11.01.2024 15:51 schrieb automate-this ***@***.***>:
FYI: I guess you should update the Text in the GUI too. Seems there are some things left from the mkp you copied. :)
image.png (view on web)

**Comment by Constey** [comment]
I've corrected that tls 1.3 will be ignored by default and i've updated the text. Thanks a lot :-)
